#!/usr/bin/env bash
#Configure nginx server so that /redirect_me is redirecting to another page.


sudo apt-get -y update
sudo apt-get -y install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
dire="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/solayof permanent;"
sudo sed -i "s/server_name _;/$dire/" /etc/nginx/sites-enabled/default
sudo service nginx restart
