#!/usr/bin/env bash
#Configure nginx server so that /redirect_me is redirecting to another page.


sudo apt-get -y update
sudo apt-get -y install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
dire="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/solayof permanent;"
sudo sed -i "s/server_name _;/$dire/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
custom_msg="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$custom_msg/" /etc/nginx/sites-enabled/default

sudo service nginx restart
