#!/usr/bin/env bash

sudo apt -y update
suod apt -y upgrade

sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.9
sudo apt-get -y update

sudo apt-get -y install haproxy-2.9.\*

config="\
frontend balancer
    bind *:80
    mode http
    default_backend lb-backends

backend lb-backends
    balance roundrobin
    server 152440-web-01 52.86.116.134:80 check
    server 152440-web-02 100.26.174.107:80 check
"
cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo echo $config >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
