#!/usr/bin/env bash

#sudo apt -y update

#sudo apt-get -y install haproxy

config="
frontend balancer
\n\t    bind *:80
\n\t    mode http
\n\t    default_backend lb-backends
\n
backend lb-backends
\n\t    balance roundrobin
\n\t    server 152440-web-01 52.86.116.134:80 check
\n\t    server 152440-web-02 100.26.174.107:80 check
"

sudo echo -e $config

#sudo service haproxy restart
