#!/usr/bin/env bash
#Bashscript that configure docker ubuntu contianer to listen to port 80
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
