#!/usr/bin/env bash
#Bashscript that configure docker ubuntu contianer to listen to port 80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
